### ISSUE TITLE
geometry collections being skipped in v0.8.x

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#106]
Special handling to encode each component part of a geometry collection was added here: https://github.com/mapbox/mapnik-vector-tile/blob/887e82a1011f02ad9ef0aa756018b03e6665c81d/src/vector_tile_processor.ipp#L799-L812 to solve #98.

However rendering osm data I encountered a situation where geometry collections still hit the `encoder_visitor` (or maybe it was the `simplify_visitor`?). Either way, this is unexpected. I would expect that if [this check](https://github.com/mapbox/mapnik-vector-tile/blob/887e82a1011f02ad9ef0aa756018b03e6665c81d/src/vector_tile_processor.ipp#L799) is working then no geometry collections would ever be encountered in the visitors. Not unless `boost::geometry::simplify` could create collections?

Anyway, this ticket captures the reason I disabled collections hastily in https://github.com/mapbox/mapnik-vector-tile/commit/dee4e3a332e8c5ee23952439b787a02057a90ce3

The next action is:

  - testcase to try to replicate a collection being passed into `handle_geometry`
  - if there are actually valid situations where a collection could be passed to `handle_geometry` (which I doubt) then we should handle them somehow instead of throwing. Perhaps we could track the original geometry type: if it was a `polygon` and then a collection of `polygon+point` was encountered we could encode the polygon and skip the point. But really I can't see how collections should even get into `handle_geometry` in the first place

**Comment by flippmoke** [comment]
A geometry collection could contain a geometry collection, therefore the logic in the check is not sufficient. I will write something to address this.

**Comment by morganherlocker** [comment]
I ran into this recently as well. 

![screenshot 2015-05-07 15 21 51](https://cloud.githubusercontent.com/assets/814300/7839305/bddd8a1c-045f-11e5-9480-f20fc5ff8d65.png)

**Comment by yhahn** [comment]
:weary:
