### ISSUE TITLE
improving stream processing of features

### ISSUE THREAD

**Issue by hjanetzek** [mapbox/mapnik-vector-tile#11]
Currently 'features = 2' are encoded in advance to 'keys = 3' and 'values = 4' [1]. When processing tile data as stream this means that feature messages cannot be processed further until keys and values are read. If features would follow keys/values one could build complete tags as soon as a feature is read and pass it down the pipeline. 
Please consider for the next protocol revision to use 'features = 6' and mark the default encoding order as required.

[1]https://developers.google.com/protocol-buffers/docs/encoding#order

**Comment by flippmoke** [comment]
I am closing this because this is something that belongs in https://github.com/mapbox/vector-tile-spec/ as it deals with the specification
