### ISSUE TITLE
Fix travis linux failures

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#118]
Need to fix https://github.com/mapbox/mason/issues/101

**Comment by danpat** [comment]
the proj package itself looks clean, it looks like mapnik-latest is bundling proj files

**Comment by springmeyer** [comment]
aha!

**Comment by springmeyer** [comment]
k, so this is likely a mason-latest package bug. Assigning to @flippmoke to take a look.

**Comment by flippmoke** [comment]
This will hopefully be fixed with https://github.com/mapnik/mapnik/commit/1377852

**Comment by springmeyer** [comment]
@flippmoke read https://github.com/mapbox/mason/issues/101. The problem I think is the `proj/proj` duplication which is likely due to the difference in `cp -r` behavior between linux and osx right here: https://github.com/mapnik/mapnik/blob/master/mason_latest.sh#L30-L32. My guess is that `cp -r $PROJ_LIB/ ${MASON_PREFIX}/share/proj/` needs to be `cp -r $PROJ_LIB ${MASON_PREFIX}/share/` to work on linux where `PROJ_LIB` cannot have a trailing slash.

**Comment by flippmoke** [comment]
Ah! Sorry, I didn't read that my bad :-1: https://github.com/mapbox/mason/commit/77839564c1851d727daf377d5b599f926bce4bfb
Corrected this as well, which I thought might have been causing the linking issues, I thought this was simply an issue of the two being different. Now correcting the trailing slashes.

**Comment by springmeyer** [comment]
nice work @flippmoke - latest build succeeded: https://travis-ci.org/mapbox/mapnik-vector-tile/jobs/67061048. Next action at https://github.com/mapbox/mason/issues/101#issuecomment-112500531
