### ISSUE TITLE
Problem with text-dy and multilinestrings

### ISSUE THREAD

**Issue by gravitystorm** [mapbox/mapnik-vector-tile#124]
I've found a bug involving text-dy and multilinestrings. I haven't been able to recreate it using non-vector-tile rendering, so I'm reporting it here.

The behaviour is that mapnik can add text labels to multilinestrings so long as the textsymbolizer `dy="0"`If `dy` is non-zero, then it sometimes fails to label at all. I haven't figured out what the characteristics of the linestrings need to be to trigger this, but I've simplified them to a bare minimum.

I've created a testcase at https://github.com/gravitystorm/mapnik-testcase-multiline-text-dy It contains a script to generate a vector tile from an inline csv, and another script to generate the raster output. It also shows some renderings.

`dy="0"`
![text-dy-zero](https://cloud.githubusercontent.com/assets/360803/8361445/2a5b021a-1b6b-11e5-92c5-fed2fdc85777.png)
`dy="1"`
![text-dy-one](https://cloud.githubusercontent.com/assets/360803/8361443/2a56a4b8-1b6b-11e5-9c0f-3eced6a303bd.png)
expected behaviour - acheived by editing the multilinestring to remove other parts
![text-dy-one-expected](https://cloud.githubusercontent.com/assets/360803/8361444/2a57cc4e-1b6b-11e5-9a2e-4444a7fbd424.png)

Let me know if I can do anything to debug this further! During debugging I thought it was related to https://github.com/mapnik/mapnik/issues/2412 but you can see from the testcase that I've taken care of that, so it's something slightly different.

**Comment by springmeyer** [comment]
Interesting, thanks @gravitystorm for reporting. In Mapnik 2.3.x `dy` used to be "dumb" and would just push text by the `dy` amount after rotating it. In 3.x now the label geometry is itself offset using the "offset_converter` that attempts to make a truly parallel line. We'll take a closer look and see what is going wrong. Thanks for the fantastic "perfect" testcase.

**Comment by flippmoke** [comment]
I noticed that your test installs two different version of node mapnik, 3.2.0 and 3.3.0, so I think this is related to the differences we have introduced between those two.

**Comment by flippmoke** [comment]
Using 3.3.1 across the board produces the same results. 
![foo](https://cloud.githubusercontent.com/assets/1794907/8363509/f0c30ece-1b44-11e5-90eb-4ec39b903a38.png)

**Comment by flippmoke** [comment]
I have notice that the offset line is the same when using the 3.2.0 branch so I do not feel the offset changes are affecting this, looking into the code that changed this result in node 3.2.0 -> 3.3.1

![foo](https://cloud.githubusercontent.com/assets/1794907/8364167/bc6aae34-1b49-11e5-83f8-f8d477f29039.png)

**Comment by flippmoke** [comment]
From what I am able to determine this seems to have been fixed by https://github.com/mapnik/mapnik/commit/5a032ee98be4daa3587110acd7a1aa61aaaffa6b

**Comment by flippmoke** [comment]
Something fixed this between mapnik 3270d42b74821ac733db169487b5cd5d5748c1e6 and the latest, it is hard to determine as 3.2.0 used the old style geometry system in mapnik and a lot of this code was redone.

**Comment by flippmoke** [comment]
@gravitystorm you can test this by changing your `package.json` to:

```
{
    "name": "buses",
    "version": "0.0.1",
    "private": true,
    "main": "./test.js",
    "description": "Example showing missing labels",
    "dependencies": {
        "mapnik": "https://github.com/mapnik/node-mapnik/tarball/master",
        "tilelive-bridge": "https://github.com/mapbox/tilelive-bridge/tarball/mapnik-3.3.1",
        "tilelive-vector": "https://github.com/mapbox/tilelive-vector/tarball/mapnik-3.3.1",
        "tilelive-file": "0.0.3",
        "tilelive": "5.7.1"
    }
}
```

**Comment by gravitystorm** [comment]
@flippmoke thank you! The updated tilelive-vector works without having to change the vector tiles (that's a big relief!) so I'll wait on the next tilelive-vector release.

Is there a unit test missing anywhere for this topic? If so, I'd be happy to help create on from my own testcase, but if it's covered now by new unit tests that's fair enough.

**Comment by flippmoke** [comment]
@gravitystorm we are needing to write a framework in node-mapnik to run all the visual tests, but I think we should definitely add your simple test to the current visual tests.
