### ISSUE TITLE
Outdated readme refers to mapnik 2.3

### ISSUE THREAD

**Issue by gravitystorm** [mapbox/mapnik-vector-tile#130]
The README in master (and in all 0.7.x and 0.8.x releases) instructs the reader to install mapnik 2.3 from packages, but these versions explicitly require mapnik 3.x

**Comment by springmeyer** [comment]
aha, good spot, thanks. Looks like https://github.com/mapbox/mapnik-vector-tile#depends has gotten updated but not the ubuntu and osx example sections. I'll circle back on this once we officially release 3.0.0: https://github.com/mapnik/mapnik/issues/2927

**Comment by flippmoke** [comment]
This is an old ticket but this might be something that @mapsame would be willing to update :+1:

**Comment by springmeyer** [comment]
Closing. Latest docs are at https://github.com/mapbox/mapnik-vector-tile#building-from-source
