### ISSUE TITLE
Make CleanPolygon call configurable/disable-able 

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#131]
Calling `ClipperLib::CleanPolygon` may discard tiny polygons at low zooms. This is generally desirable if your priority is reducing vtile sizes. But this may not be desirable in certain situations.

Take for instance: making maps at low zoom levels of polynesian islands.

Here is an example of a `MarkersSymbolizer` on each polygon when rendering shp->png directly (no vector tile encoding):

![nz-1](https://cloud.githubusercontent.com/assets/20300/8417321/9ec79120-1e60-11e5-8d21-8f9e99bde74d.png)

However when rendered to a vtile and back to an image we loose many of the small islands:

![nz-1-actual](https://cloud.githubusercontent.com/assets/20300/8417338/c4c98f54-1e60-11e5-8ee7-303a874920bb.png)

After disabling `CleanPolygon` we regain most of the small islands:

![nz-1-actual-noclean](https://cloud.githubusercontent.com/assets/20300/8417334/bd34cba0-1e60-11e5-8d2f-bb10f0071652.png)

NOTE: `area_threshold` in these tests was set to `0.0` so the islands are not being thrown away due to that parameter.

One potential solution - for cartographic or other use cases where loosing small polygons is not okay -would be to offer a mode where polygons are collapsed to points rather than thrown away. But in the short term I think the best solution is to provide an option to disable cleaning polygons.

**Comment by flippmoke** [comment]
I wonder if this should actually be configurable, because my hunch is that these small islands are invalid polygons.

**Comment by flippmoke** [comment]
This pull request is closed because the CleanPolygon process has been replaced as part of the introduction of wagyu over the angus clipper.
