### ISSUE TITLE
Skip geometry parts that do not intersect in any way with the clipping bounding box.

### ISSUE THREAD

**Issue by flippmoke** [mapbox/mapnik-vector-tile#134]
As an alternative to #126 @springmeyer and I have been discussing the potential to skip geometry parts that are not are not required for the clipper, this could be considered a pre clipping state to reduce the amount of points that would have to go through reprojection into the integer domain of the vector tile.

**Comment by springmeyer** [comment]
closed by #135 - summarized at https://github.com/mapbox/mapnik-vector-tile/pull/135#issuecomment-125307345. Great job on this work @flippmoke!
