### ISSUE TITLE
Unexpected exception in vector_tile_pbf.cpp

### ISSUE THREAD

**Issue by tomhughes** [mapbox/mapnik-vector-tile#168]
Running the tests I get a failure:

```
-------------------------------------------------------------------------------
pbf decoding garbage buffer
-------------------------------------------------------------------------------
../test/vector_tile_pbf.cpp:319
...............................................................................

../test/vector_tile_pbf.cpp:319: FAILED:
due to unexpected exception with message:
  unknown pbf field type exception
```

This is apparently because the `pbf_tile.next();` line is throwing an exception before we get to the line that the test is expecting to throw.

**Comment by flippmoke** [comment]
@tomhughes I am sorry I ignored this issue, but was in the process of a major rewrite as part of work for the v2_spec. 

Yes, that is an error in protozero, I am not sure what was causing that, but it should hopefully be resolved with the v2_spec. I haven't seen any errors like this in master currently.

**Comment by flippmoke** [comment]
I am closing this issue because I have pulled into master a large number of changes that were in the `v2_spec`, if there is another other issue found please file a new issue! (aka it has more then likely already been fixed)
