### ISSUE TITLE
incorrect handling of optional fields

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#17]
We have several fields in the proto that are marked optional but are expected to exist as far as how the code implementation works:

 - feature `id`
 - layer `extent`
 - feature `geomType`.

feature `id` in particular does not have a default.

We need to either change the proto file or adapt the code.

**Comment by flippmoke** [comment]
This is now something that is addressed as part of the https://github.com/mapbox/vector-tile-spec/. The code has been updated to follow this standard.
