### ISSUE TITLE
Disable geometry clipping?

### ISSUE THREAD

**Issue by JelmerBaas** [mapbox/mapnik-vector-tile#172]
First off: Apologies if this is the wrong place to ask.

I'm currently playing around with tilestrata, mapnik and mapnik vector tiles. My target software doesn't have the ability to cut off the buffer part of a vector tile, meaning I end up with a lot of horizontal and vertical lines. I wouldn't mind having two identical geometries overlap; so I think somehow disabling geometry clipping all together would be a good solution.

Is there any way to disable geometry clipping?

**Comment by flippmoke** [comment]
It would not be a valid polygon if it did not create an edge on the boundary of the tile (assuming it extents past the bounds of the tile.)
