### ISSUE TITLE
feature id type is incorrect in proto

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#18]
It is listed as `uint64` but in fact feature ids can be negative in mapnik (to support OSM negative ids) and the type is `long long` (`mapnik::value_integer`). We either need to change the proto or (more ideally) implement zigzag encoding at both tile encoding and decoding.

This will be a breaking change to the tile format.

**Comment by flippmoke** [comment]
This would require a change to https://github.com/mapbox/vector-tile-spec/ therefore, closing this ticket.
