### ISSUE TITLE
Overhead in std::launch::deferred

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#183]
Profiling `./build/Release/vtile-encode ./test/geometry-test-data/input/counter-clockwise-polygon.json 0 0 0 -i 100000000` with `Activity Monitor` shows significant (> 2 %) of time taken in `std::future` and `std::async::deferred` usage. This says to me that locks are being invoked even when we are running synchronously, which is bad and indicates we may want to re-write to not use futures when we are not using `std::launch::async` (assuming this also impacts linux):

![screen shot 2016-01-26 at 4 01 02 pm](https://cloud.githubusercontent.com/assets/20300/12599376/3d9a18dc-c446-11e5-91a2-aecedbea2c8c.png)

![screen shot 2016-01-26 at 4 00 42 pm](https://cloud.githubusercontent.com/assets/20300/12599384/51ece26a-c446-11e5-9ebd-381a088dcb7e.png)

**Comment by flippmoke** [comment]
This has been addressed already and deferred launch does not require calling to std async.
