### ISSUE TITLE
error: no matching function for call to ‘range_by_section

### ISSUE THREAD

**Issue by strk** [mapbox/mapnik-vector-tile#190]
On an ubuntu 14.04:

```
/usr/include/boost/geometry/algorithms/detail/overlay/get_turns.hpp:177:60: error: no matching function for call to ‘range_by_section(const mapnik::geometry::multi_line_string<double>&, const boost::geometry::section<boost::geometry::model::box<mapnik::geometry::point<double> >, 2ul>&)’
         cview_type1 cview1(range_by_section(geometry1, sec1));
                                                            ^
```

Sounds like a dejavu (Mapnik itself has the same issue?) -- anyway, better reported here I'd think.

**Comment by flippmoke** [comment]
@strk what version of boost geometry?

**Comment by strk** [comment]
libboost1.54-dev: /usr/include/boost/geometry/algorithms/detail/overlay/get_turns.hpp
1.54.0-4ubuntu3.1

**Comment by flippmoke** [comment]
@strk Try using at least boost 1.58

**Comment by flippmoke** [comment]
Also see https://github.com/mapnik/mapnik/issues/3368 -- we are talking about the requirements right now

**Comment by flippmoke** [comment]
I am closing this ticket and tracking it now in #612

**Comment by flippmoke** [comment]
@strk can you verify that boost 1.54 works after my latest [commit](https://github.com/mapbox/mapnik-vector-tile/commit/5ba89b8196e312d6f357405c34a2ac6ece4c06a6) -- Just a heads up you will need the latest version of mapnik for the tests to build properly after a header changed in mapnik.

**Comment by strk** [comment]
As of 1ab33002e77e8c7d3a271c251d1dc2a17a66b5f7 it still fails for me.
An example error:
```
/usr/include/boost/geometry/algorithms/within.hpp:289:17: error: no type named ‘type’ in ‘struct boost::geometry::strategy::within::services::default_strategy<boost::geometry::point_tag, boost::geometry::multi_linestring_tag, boost::geometry::point_tag, boost::geometry::multi_linestring_tag, boost::geometry::cartesian_tag, boost::geometry::cartesian_tag, mapnik::geometry::point<double>, mapnik::geometry::multi_line_string<double> >’
```

**Comment by springmeyer** [comment]
Docs have been updated at https://github.com/mapbox/mapnik-vector-tile#building-from-source. Please create new issues if still having trouble.
