### ISSUE TITLE
Test coverage of mapnik::vector_tile_impl::tile_layer

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#202]
While trying to fix a bug I think is inside the new `tile_layer` class I noticed the tests for this class are commented: https://github.com/mapbox/mapnik-vector-tile/blob/master/test/unit/tile_impl/tile.cpp#L195-L338

Looks like they were disabled @flippmoke  in https://github.com/mapbox/mapnik-vector-tile/commit/a9e306b6f4e2078519e86538c21f42bf782a67dc#diff-500e66444d0e17c2ca2cf308f8b81497L193

**Comment by flippmoke** [comment]
These where old tests prior to the changes in the layer class, I have removed them.
