### ISSUE TITLE
Move back to mapnik::is_clockwise

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#208]
Once Mapnik core v3.0.12 is released we can move back to using its fixed `is_clockwise` implementation which was discarded in https://github.com/mapbox/mapnik-vector-tile/commit/5f9059bec189e2fc2cd67ae3a25852aaaee638c9 and mirrored in https://github.com/mapbox/mapnik-vector-tile/commit/69aab12cca534fced2aefd2ecce5f4c08facf1ad#commitcomment-17174189

**Comment by flippmoke** [comment]
@springmeyer we no longer use is_clockwise or the previous mirrored version.

**Comment by springmeyer** [comment]
Ah, thanks @flippmoke
