### ISSUE TITLE
I'm not a c++ programmer,how can i use it in command line?

### ISSUE THREAD

**Issue by wandergis** [mapbox/mapnik-vector-tile#211]
I'm very interesting with vector-tile,but i'm not a c++ programmer,so i don't know how to use it make vector tile even I hava  run `make` command, and  got these  files as it below.
![image](https://cloud.githubusercontent.com/assets/5799374/15067800/8a8e5712-13a5-11e6-9d77-eda2d7711320.png)
How can i use it to build vector tile? Does there is some arcticles or blogs tell how to do with it?

Thanks very much.

**Comment by flippmoke** [comment]
I would suggest you use node-mapnik to make vector tiles, as it will be a much easier interface. If you are not wanting to write C++ code this library is not the one you should use. You might look into tippecanoe or tilelive as well.

**Comment by wandergis** [comment]
Thanks a lot！I will try your suggestion.
