### ISSUE TITLE
mapnik::attributes variables (to replace @tokens in postgis SQL sub-queries)

### ISSUE THREAD

**Issue by aleksejleonov** [mapbox/mapnik-vector-tile#218]
Is there any ability to set `mapnik::attributes` variables (used to replace **@tokens** in postgis SQL sub-queries) for rendering VectorTiles?

As example, with default mapnik raster tiles rendering it works next way:

``` C++
mapnik::attributes vars;
// ... setting vars
mapnik::agg_renderer<mapnik::image_rgba8> ren(map, req, vars, im, scale_factor, 0, 0);
```

But looks like there no ability to set this variables with `mapnik::vector_tile_impl::processor` (https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_processor.hpp#L50).

**Comment by springmeyer** [comment]
Solved in #248 thanks to @rafatower
