### ISSUE TITLE
Issue with "mapnik-vector-tile" and Mapnik 3.0.12

### ISSUE THREAD

**Issue by Mahmoud-Moustafa** [mapbox/mapnik-vector-tile#224]
I followed the instructions in the README.md but when I execute the command "make" I get the following error:

In file included from ../src/vector_tile_tile.hpp:8:0,
                 from ../src/vector_tile_processor.hpp:14,
                 from ../test/geometry_visual_test.cpp:6:
../deps/protozero/include/protozero/pbf_reader.hpp: In constructor ‘protozero::pbf_reader::pbf_reader(const char*, std::size_t)’:
../deps/protozero/include/protozero/pbf_reader.hpp:161:9: warning: declaration of ‘length’ shadows a member of 'this' [-Wshadow]
         : m_data(data),
         ^
../deps/protozero/include/protozero/pbf_reader.hpp: In member function ‘bool protozero::pbf_reader::next(protozero::pbf_tag_type)’:
../deps/protozero/include/protozero/pbf_reader.hpp:320:33: warning: declaration of ‘tag’ shadows a member of 'this' [-Wshadow]
     bool next(pbf_tag_type tag) {
                                 ^
In file included from ../src/vector_tile_processor.hpp:14:0,
                 from ../test/geometry_visual_test.cpp:6:
../src/vector_tile_tile.hpp: In constructor ‘mapnik::vector_tile_impl::tile::tile(const mapnik::box2d<double>&, uint32_t, int32_t)’:
../src/vector_tile_tile.hpp:43:9: warning: declaration of ‘buffer_size’ shadows a member of 'this' [-Wshadow]
         : buffer_(),
         ^
../src/vector_tile_tile.hpp:43:9: warning: declaration of ‘tile_size’ shadows a member of 'this' [-Wshadow]
../src/vector_tile_tile.hpp:43:9: warning: declaration of ‘extent’ shadows a member of 'this' [-Wshadow]
In file included from ../src/vector_tile_processor.hpp:15:0,
                 from ../test/geometry_visual_test.cpp:6:
../src/vector_tile_merc_tile.hpp: In constructor ‘mapnik::vector_tile_impl::merc_tile::merc_tile(uint32_t, uint32_t, uint32_t, uint32_t, int32_t)’:
../src/vector_tile_merc_tile.hpp:26:9: warning: declaration of ‘buffer_size’ shadows a member of 'this' [-Wshadow]
         : tile(merc_extent(tile_size, x, y, z), tile_size, buffer_size),
         ^
../src/vector_tile_merc_tile.hpp:26:9: warning: declaration of ‘tile_size’ shadows a member of 'this' [-Wshadow]
../src/vector_tile_merc_tile.hpp:26:9: warning: declaration of ‘z’ shadows a member of 'this' [-Wshadow]
../src/vector_tile_merc_tile.hpp:26:9: warning: declaration of ‘y’ shadows a member of 'this' [-Wshadow]
../src/vector_tile_merc_tile.hpp:26:9: warning: declaration of ‘x’ shadows a member of 'this' [-Wshadow]
../src/vector_tile_merc_tile.hpp: In member function ‘void mapnik::vector_tile_impl::merc_tile::x(uint32_t)’:
../src/vector_tile_merc_tile.hpp:48:5: warning: declaration of ‘x’ shadows a member of 'this' [-Wshadow]
     {
     ^
../src/vector_tile_merc_tile.hpp: In member function ‘void mapnik::vector_tile_impl::merc_tile::y(uint32_t)’:
../src/vector_tile_merc_tile.hpp:59:5: warning: declaration of ‘y’ shadows a member of 'this' [-Wshadow]
     {
     ^
../src/vector_tile_merc_tile.hpp: In member function ‘void mapnik::vector_tile_impl::merc_tile::z(uint32_t)’:
../src/vector_tile_merc_tile.hpp:70:5: warning: declaration of ‘z’ shadows a member of 'this' [-Wshadow]
     {
     ^
../test/geometry_visual_test.cpp: In function ‘void clip_geometry(const mapnik::Map&, const string&, const mapnik::box2d<double>&, int, bool, mapnik::vector_tile_impl::polygon_fill_type, bool, bool)’:
../test/geometry_visual_test.cpp:98:17: error: ‘is_valid’ is not a member of ‘mapnik::geometry’
             if (mapnik::geometry::is_valid(geom4326_pbf, reason))
                 ^
../test/geometry_visual_test.cpp:98:17: note: suggested alternative:
In file included from /usr/local/include/mapnik/datasource.hpp:31:0,
                 from /usr/local/include/mapnik/memory_datasource.hpp:27,
                 from ../test/test_utils.hpp:5,
                 from ../test/geometry_visual_test.cpp:22:
/usr/local/include/mapnik/featureset.hpp:60:13: note:   ‘mapnik::is_valid’
 inline bool is_valid(featureset_ptr const& ptr)
             ^
../test/geometry_visual_test.cpp:102:17: error: ‘is_simple’ is not a member of ‘mapnik::geometry’
             if (mapnik::geometry::is_simple(geom4326_pbf))

Can you please help me in installing/using "mapnik-vector-tile" since I find it difficult, specially, cause I don't have any experience with C++

**Comment by springmeyer** [comment]
Please try again, latest master is working better now. Just type `make`. If you still hit problems please create a new issue.
