### ISSUE TITLE
Visual test failure

### ISSUE THREAD

**Issue by artemp** [mapbox/mapnik-vector-tile#225]
https://github.com/mapbox/mapnik-vector-tile/tree/develop-master built with mapnik/master results in following visual test failure 

```bash
geometries visual tests
-------------------------------------------------------------------------------
../test/geometry_visual_test.cpp:245
...............................................................................

../test/geometry_visual_test.cpp:159: FAILED:
  CHECK( expected_string == geojson_string )
with expansion:
  "{"type":"Polygon","coordinates":[[[4041072.50477517,-1354770.194624],
  [4040086.3975408,-1354770.194624],[4040086.3975408,-1354772.88156469],
  [4040090.42795184,-1354776.91197573],[4040091.77142219,-1354776.91197573],

< -- skip lots of coordinates -- >

 [4038600.51933752,-1354962.31088356],[4038605.8932189,-1354960.96741321],
  [4038609.92362994,-1354960.96741321],[4038615.29751133,-1354959.62394286],
... message truncated due to excessive size

../test/utils/geometry_equal.hpp:132: FAILED:
  REQUIRE( false )
```

#### Input file

The input file in question is : `/test/geometry-test-data/output/clipper-firstleft-bug/4.03557e+06,-1.36027e+06,4.04107e+06,-1.35477e+06,simplify_distance=0,strictly_simple=0,fill_type=0,mpu=0,par=0.geojson`

#### Both `expected` and `actual` geometries loaded in OpenJUMP 

<img width="833" alt="diff" src="https://cloud.githubusercontent.com/assets/59056/21051997/13705d8c-be23-11e6-9742-d31b062833f7.png">

It looks like a simplification issue ?? 

I don't feel that running  ```UPDATE=1 make test``` is the correct approach here as I don't understand background for this test. @flippmoke could you investigate the cause of this particular failure and give green light to UPDATE or how to proceed otherwise, please. 

/cc @springmeyer @flippmoke

**Comment by artemp** [comment]
Please, note expected (brown) geometry is ~10x larger than actual (green)
/cc @flippmoke @springmeyer

**Comment by artemp** [comment]
[mapnik-vector-tile-#225.tar.gz](https://github.com/mapbox/mapnik-vector-tile/files/642483/mapnik-vector-tile-.225.tar.gz)
Here are expected and actual geometries in WKT and GeoJSON formats.

**Comment by flippmoke** [comment]
This has to do with updating prematurely master of `geometry-test-data` for the `wagyu` branch of MVT - it should have been done on another branch, but was not because I expected things to go smoother then they did.

**Comment by artemp** [comment]
@flippmoke - thanks for looking into this.
