### ISSUE TITLE
Problem with mapnik-vector-tile

### ISSUE THREAD

**Issue by nixadmin** [mapbox/mapnik-vector-tile#238]
Hello. 
When we run the C++ tests with "make test". We have error:
make[1]: Leaving directory '/root/nix/artemt/mapnik-vector-tile/build'
DYLD_LIBRARY_PATH= ./build/Release/tests
./build/Release/tests: symbol lookup error: ./build/Release/tests: undefined symbol: _ZN6mapnik16datasource_cache20register_datasourcesERKSsb
Makefile:24: recipe for target 'test' failed
make: *** [test] Error 127

Can you help us resolve it?
Thanks

**Comment by flippmoke** [comment]
@nixadmin what version of mapnik are you using?

**Comment by flippmoke** [comment]
Closing this ticket from a lack of a response.
