### ISSUE TITLE
clipper function matching?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/mapnik-vector-tile#249]
/home/vagrant/mapnik-vector-tile-1.2.2/src/vector_tile_geometry_clipper.hpp:54:59: error: no matching function for call to ‘mapnik::geometry::polygon<long int>::set_exterior_ring(std::remove_reference<std::vector<ClipperLib::IntPoint>&>::type)’

mapnik-vector-tile-1.2.2 was compiled ok,but when i try to use it, it come up with this error.

**Comment by flippmoke** [comment]
What version of mapnik are you attempting to compile against?

**Comment by lihuadong1988** [comment]
mapnik v3.0.12

**Comment by springmeyer** [comment]
We've replace clipper with wagyu in #227. If you are still having trouble, please create a new issue.
