### ISSUE TITLE
Mapnik Format string

### ISSUE THREAD

**Issue by jucajuca** [mapbox/mapnik-vector-tile#250]
Hello,
which would be the Mapnik Format string to generate vector tiles?
See here https://github.com/mapnik/mapnik/wiki/Image-IO

thx!

**Comment by springmeyer** [comment]
@jucajuca vector tiles are not created via a format string. They are rendered in a very different way. See http://mapnik.org/documentation/node-mapnik/3.6/#VectorTile for API docs on how to create them. Or use a command line tool like https://github.com/mapbox/tippecanoe
