### ISSUE TITLE
0.6.x polygon clip error

### ISSUE THREAD

**Issue by haoziluo** [mapbox/mapnik-vector-tile#260]
when clip polygon geometry to vt is error with boundary, I convert vt to geojson, like this:
![2017-11-28 16 00 45](https://user-images.githubusercontent.com/2647388/33308478-90b1193c-d455-11e7-883c-eb5015114f75.png)
but clip polyline geometry is ok.

**Comment by flippmoke** [comment]
@haoziluo can you please provide a test case for this?

**Comment by haoziluo** [comment]
the source mvt file: [test.mvt.zip](https://github.com/mapbox/mapnik-vector-tile/files/1512332/test.mvt.zip)

**Comment by haoziluo** [comment]
I try to render the same source with tangram, is ok. So It's version reason? I found the console warn '_Vector tile source "vt" layer "BPbeijing_L_T_N" does not use vector tile spec v2 and therefore may have some rendering errors._' in browser.
