### ISSUE TITLE
mapnik-vector-tile is very slow when data is too big?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/mapnik-vector-tile#265]

**Comment by flippmoke** [comment]
Could you please provide more information around this bug report? A repeatable example is highly important in debugging problems such as these.

**Comment by lihuadong1988** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Map srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" buffer-size="10">
    <Layer name="roads_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <Datasource>
            <Parameter name="type">ogr</Parameter>
            <Parameter name="base">/data</Parameter>
            <Parameter name="file">dbfg.gdb</Parameter>
            <Parameter name="layer">DBSJ_DLGQDBFG_YD_PY</Parameter>
            <Parameter name="simplify">true</Parameter>
        </Datasource>
    </Layer>
    <Layer name="water_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"> 
        <Datasource>
            <Parameter name="type">ogr</Parameter>
            <Parameter name="base">/data</Parameter>
            <Parameter name="file">dbfg.gdb</Parameter>
            <Parameter name="layer">DBSJ_DLGQDBFG_CD_PY</Parameter>
            <Parameter name="simplify">true</Parameter>
        </Datasource>
    </Layer>
</Map>

    this is my mapnik style file,source gdb file is about 9GB. below is my source code to generate mvt. it takes me seconds to generate one single tile.

    WebMercator2lonLat(&minx,&miny);
    WebMercator2lonLat(&maxx,&maxy);
    
    box2d<double> bbox;

    bbox.init(minx, miny, maxx, maxy);

    tile_map.zoom_to_box(bbox);
    
    vector_tile::Tile tile;
    mapnik::vector_tile_impl::backend_pbf backend(tile, path_multiplier);
    request mapnik_request(tile_size, tile_size, bbox);
    mapnik_request.set_buffer_size(5);
    mapnik::vector_tile_impl::processor<mapnik::vector_tile_impl::backend_pbf> ren(backend, tile_map, mapnik_request);

**Comment by lihuadong1988** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Map srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" buffer-size="10">
    <Layer name="roads_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <Datasource>
            <Parameter name="type">ogr</Parameter>
            <Parameter name="base">/data</Parameter>
            <Parameter name="file">dbfg.gdb</Parameter>
            <Parameter name="layer">DBSJ_DLGQDBFG_YD_PY</Parameter>
            <Parameter name="simplify">true</Parameter>
        </Datasource>
    </Layer>
    <Layer name="water_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"> 
        <Datasource>
            <Parameter name="type">ogr</Parameter>
            <Parameter name="base">/data</Parameter>
            <Parameter name="file">dbfg.gdb</Parameter>
            <Parameter name="layer">DBSJ_DLGQDBFG_CD_PY</Parameter>
            <Parameter name="simplify">true</Parameter>
        </Datasource>
    </Layer>
</Map>

**Comment by lihuadong1988** [comment]
<Map srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" buffer-size="10">
    <Layer name="roads_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <Datasource>
            <Parameter name="type">ogr</Parameter>
            <Parameter name="base">/data</Parameter>
            <Parameter name="file">dbfg.gdb</Parameter>
            <Parameter name="layer">DBSJ_DLGQDBFG_YD_PY</Parameter>
            <Parameter name="simplify">true</Parameter>
        </Datasource>
    </Layer>
    <Layer name="water_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"> 
        <Datasource>
            <Parameter name="type">ogr</Parameter>
            <Parameter name="base">/data</Parameter>
            <Parameter name="file">dbfg.gdb</Parameter>
            <Parameter name="layer">DBSJ_DLGQDBFG_CD_PY</Parameter>
            <Parameter name="simplify">true</Parameter>
        </Datasource>
    </Layer>
</Map>

**Comment by lihuadong1988** [comment]
<?xml version="1.0" encoding="utf-8"?>
Map srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" buffer-size="10">
    <Layer name="roads_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        <Datasource>
            <Parameter name="type">ogr</Parameter>
            <Parameter name="base">/data</Parameter>
            <Parameter name="file">dbfg.gdb</Parameter>
            <Parameter name="layer">DBSJ_DLGQDBFG_YD_PY</Parameter>
            <Parameter name="simplify">true</Parameter>
        </Datasource>
    </Layer>
    <Layer name="water_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"> 
        <Datasource>
            <Parameter name="type">ogr</Parameter>
            <Parameter name="base">/data</Parameter>
            <Parameter name="file">dbfg.gdb</Parameter>
            <Parameter name="layer">DBSJ_DLGQDBFG_CD_PY</Parameter>
            <Parameter name="simplify">true</Parameter>
        </Datasource>
    </Layer>
Map>

**Comment by lihuadong1988** [comment]
<?xml version="1.0" encoding="utf-8"?>
Map srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" buffer-size="10">
    Layer name="roads_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
        Datasource>
            Parameter name="type">ogr</Parameter>
            Parameter name="base">/data</Parameter>
            Parameter name="file">dbfg.gdb</Parameter>
            Parameter name="layer">DBSJ_DLGQDBFG_YD_PY</Parameter>
            Parameter name="simplify">true</Parameter>
        /Datasource>
    /Layer>
Map>

**Comment by lihuadong1988** [comment]
Map srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" buffer-size="10">
Layer name="roads_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
Datasource>
Parameter name="type">ogr
Parameter name="base">/data
Parameter name="file">dbfg.gdb
Parameter name="layer">DBSJ_DLGQDBFG_YD_PY
Parameter name="simplify">true
/Datasource>
/Layer>
Map>
this is my mapnik style file. below is my source file to generate mvt.

    WebMercator2lonLat(&minx,&miny);
    WebMercator2lonLat(&maxx,&maxy);
    
    box2d<double> bbox;

    bbox.init(minx, miny, maxx, maxy);

    tile_map.zoom_to_box(bbox);
    
    vector_tile::Tile tile;
    mapnik::vector_tile_impl::backend_pbf backend(tile, path_multiplier);
    request mapnik_request(tile_size, tile_size, bbox);
    mapnik_request.set_buffer_size(5);
    mapnik::vector_tile_impl::processor<mapnik::vector_tile_impl::backend_pbf> ren(backend, tile_map, mapnik_request);

when i use this to generate mvt, it takes minutes to generate one single tile.

**Comment by lihuadong1988** [comment]
Map srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" buffer-size="10">
Layer name="roads_sc" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
Datasource>
Parameter name="type">ogr
Parameter name="base">/data
Parameter name="file">dbfg.gdb
Parameter name="layer">DBSJ_DLGQDBFG_YD_PY
Parameter name="simplify">true
/Datasource>
/Layer>
Map>

this is my mapnik style file. below is my source code to generate mvt.

    mapnik::vector_tile_impl::spherical_mercator merc(tile_size);
    merc.xyz(x, y, z, minx, miny, maxx, maxy);

    WebMercator2lonLat(&minx,&miny);
    WebMercator2lonLat(&maxx,&maxy);

    box2d<double> bbox;
    bbox.init(minx, miny, maxx, maxy);

    tile_map.zoom_to_box(bbox);

    mapnik::vector_tile_impl::processor ren(tile_map);
    
    ren.set_simplify_distance(5.0);
    ren.set_threading_mode(std::launch::async);
       
    mapnik::vector_tile_impl::tile out_tile = ren.create_tile(bbox,tile_size);

it took me minutes to generate one single tile?what's wrong?

**Comment by lihuadong1988** [comment]
i'm using mapnik-vector-tile 1.2.0 with mapnik v3.0.9.

**Comment by flippmoke** [comment]
My initial guess here is that you are querying large amounts of data from your `gdb` that must be processed every time you are looking to create a tile. If a single tile is covering your entire dataset, it may take quite a while to simply create. With out knowing exactly what your data is like and how you have it indexed it is very difficult for me to point at any particular thing that might help you speed up the process.

**Comment by pnorman** [comment]
I'd agree, this is not mapnik-vector-tile being slow, but the map layers being slow. I expect they would be just as slow if you were only using Mapnik and rendering a raster. As @flippmoke alluded to, it's probably an issue with the data being queried.

I wouldn't recommend using mapnik-vector-tile with anything other than PostGIS because there are some things that are just too hard to do with the other Mapnik drivers, like have zoom-dependent layers.

**Comment by lihuadong1988** [comment]
I know where the problem is. mapnik uses openfilegdb as gdb driver，but openfilegdb does not support gdb index like .spx, as a result, spatial queries are very slow.if i use filegdb as gdb dirver,the problem will be solved.
