### ISSUE TITLE
[MVT] Query resolution based on 256 extent instead of vector_layer_extent

### ISSUE THREAD

**Issue by Algunenano** [mapbox/mapnik-vector-tile#289]
Lately I've been investigating one issue around MVTs using the Postgis plugin to retrieve the geometries from the database and found that, when using the `simplify_geometries` parameter, the geometries are simplified considering a `256` pixel size, not a `vector_layer_extent` size.

Consider the attached xml ([postgis_simplification.txt](https://github.com/mapbox/mapnik-vector-tile/files/2224616/postgis_simplification.txt)), or this extract:
```xml
       <Parameter name="simplify_geometries"><![CDATA[true]]></Parameter>
       <Parameter name="twkb_encoding"><![CDATA[true]]></Parameter>
       <Parameter name="vector_layer_extent"><![CDATA[4096]]></Parameter>
```

Following the [twkb tolerance calculation](https://github.com/mapnik/mapnik/blob/70fbdd21c7879d9d46afe0fbdacbfecbb7fed37e/plugins/input/postgis/postgis_datasource.cpp#L787) when requesting a tile of zoom 12, (12,12,12) we should have:
* Extent: 40075017 / 2^12 = 9783.939697
* Resolution: $extent / 4096 = 2.388657153
* Tolerance: POW(10, ROUND(LOG10($resolution)) - 1) = **0.1** 

Instead we see this query:
```sql
SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints("the_geom",10),10,true),-1) AS geom,"cartodb_id" FROM (SELECT 2 AS cartodb_id, 'SRID=3857;LINESTRING(0 20037508, 0 0, 0 10037508, 0 -10037508, 0 -20037508)'::geometry as the_geom) as cdbq WHERE "the_geom" && ST_SetSRID('BOX3D(-19959236.82582522 19871181.3692407,-19871181.3692407 19959236.82582522)'::box3d, 3857)
```
Which comes from using 256 as the extent:
* Extent: 40075017 / 2^12 = 9783.939697
* Resolution: $extent / 256 = 38.21851444
* Tolerance: POW(10, ROUND(LOG10($resolution)) - 1) = **10**

This means that for a 4096 tile we are having a tolerance 100 times bigger than expected which leads to oversimplification and partially breaking the ability of over-zooming. 
It is even more painful if you try to do some kind of one-tile-optimization (request a big part of the map with less or no simplification), for example requesting the tile (0,0,0) with an extent of 256*2^18 and simplifying in the client. As the requested extent isn't being considered, the geometries will just disappear due to the simplification.

I've been investigating and this hasn't always been like this. It used to be just `layer_extent_ / qw` (which is what I expected and want in this case), but it was modified in 041aed410dd147b4beeebd1723f452268a018a83 to use `image_size` instead, and then modified to its current status in 75c4868d0900963c19e0adcd00ec8d5c87572a57 to use `VT_LEGACY_IMAGE_SIZE`:
https://github.com/mapbox/mapnik-vector-tile/blob/61aebcbaf4552dc410a8bdbbe09f9e5d7cbbb076/src/vector_tile_layer.hpp#L331-L340

@flippmoke Could you please shed some light on this? Is there any special requirement to maintain the 256 there? I've changed it locally and it passes all the tests. Should I open a PR with the change?

**Comment by flippmoke** [comment]
The short answer, I can't entirely recall why this was section of code was coded this way. My assumption is that it was likely to match the legacy system which used to base a lot of this based on a assumed image size of 256. I am not sure we need to maintain this value anymore and it would likely make sense to change it. You should feel free to open a PR, but I think we would want to test it against `node-mapnik` before merging to see if any results are drastically different.

**Comment by Algunenano** [comment]
I've opened https://github.com/mapbox/mapnik-vector-tile/pull/290 which addresses this.

With this change there isn't any impact in our [node-mapnik fork](https://travis-ci.org/Algunenano/node-mapnik/builds/408085522) tests, which is based on mapnik 3.0, but I'll check with node-mapnik master (3.1/4.0) to make sure.
Probably there will be some differences in tilelive-bridge as it compares json's. I'll have a more detailed look and let you know my findings.

**Comment by Algunenano** [comment]
Test of different modules:
- mapnik-vector-tile (https://github.com/mapbox/mapnik-vector-tile/pull/290): [Build passes without changes needed for tests](https://travis-ci.org/mapbox/mapnik-vector-tile/builds/408091234)
- node-mapnik (https://github.com/Algunenano/node-mapnik/commit/4b6870f37b1e98cb23c8afbddbbaab5caee1af23): [Build passes without changes needed for tests](https://travis-ci.org/Algunenano/node-mapnik/builds/408953343)
- tilelive-bridge (https://travis-ci.org/Algunenano/tilelive-bridge/jobs/408960384). The build in Travis isn't valid since it's using the static compilation of the module (not including the changes to mapnik-vector-tile). I tested it locally by symlinking the appropriate node-mapnik module directory and also there wasn't any failed test.

The main problem I see is if all the test are clean it is probably because there isn't any testing simplification, at least not with the postgis plugin. I guess this change doesn't affect the general usage of MVTs in node-mapnik.
One I reach Windshaft I do see differences in some tests: for example in [this one](https://github.com/CartoDB/Windshaft/blob/ba18a513cb7a5fcfd5108187da81fcd7c8d36938/test/acceptance/mvt.js#L977) the geometry used to be returned with just 6 points and now it has 18. Using St_AsMVT (straight out of Postgis) it has 14, but that's a different battle.

**Comment by pnorman** [comment]
This would be a breaking change and need to go out in a major version of node-mapnik, and if this project follows semver, this one too.

**Comment by flippmoke** [comment]
Just a quick review for myself of this.. This qw and qh is used to create a `mapnik::resolution` then a`mapnik::query` object that is used [here](https://github.com/mapbox/mapnik-vector-tile/blob/26d4c6fecdf7a73a9556868d48c96d9660706462/src/vector_tile_layer.hpp#L355). 

This will change the request from our vector plugins in mapnik so it will be used in the following locations:

* [geojson plugin](https://github.com/mapnik/mapnik/blob/master/plugins/input/geojson/geojson_datasource.cpp#L567)
* [ogr plugin](https://github.com/mapnik/mapnik/blob/master/plugins/input/ogr/ogr_datasource.cpp#L522)
* [postgis plugin](https://github.com/mapnik/mapnik/blob/master/plugins/input/postgis/postgis_datasource.cpp#L707)
* [sqlite plugin](https://github.com/mapnik/mapnik/blob/master/plugins/input/sqlite/sqlite_datasource.cpp#L488)
* [shapefile plugin](https://github.com/mapnik/mapnik/blob/master/plugins/input/shape/shape_datasource.cpp#L233)
* [geobuf plugin](https://github.com/mapnik/mapnik/blob/master/plugins/input/geobuf/geobuf_datasource.cpp#L222)
* [csv plugin](https://github.com/mapnik/mapnik/blob/master/plugins/input/csv/csv_datasource.cpp#L388)
* [topojson plugin](https://github.com/mapnik/mapnik/blob/master/plugins/input/topojson/topojson_datasource.cpp#L277)

The only way this would be accessed if the `mapnik::query` object then used the `resolution()` method, so is this even used for Vectors? I do not see `resolution()` called in any of the Vector plugins does this even change anything?

Am I missing something?

**Comment by Algunenano** [comment]
In the Postgis plugin it is used [here](https://github.com/mapnik/mapnik/blob/74b2886036f9440975615d2bee256c990fe0238c/plugins/input/postgis/postgis_datasource.cpp#L773) since it is needed to decide the parameters passed to St_AsTWKB or St_Simplify.

I didn't check any other plugin; I'll try to have a look tomorrow.

**Comment by Algunenano** [comment]
The 2 usages that I found and in the [Postgis plugin](https://github.com/mapnik/mapnik/blob/74b2886036f9440975615d2bee256c990fe0238c/plugins/input/postgis/postgis_datasource.cpp#L773) and in [Pgraster](https://github.com/mapnik/mapnik/blob/74b2886036f9440975615d2bee256c990fe0238c/plugins/input/postgis/postgis_datasource.cpp#L773).

To explain a bit further: We use the Postgis plugin to retrieve the geometries already simplified from the database to reduce network load (different servers) and `mapnik-vector-tile` to generate the MVT based on those geometries. As we have already simplified the geometries, we turn off `simplify_distance` in the `map.render` call.

If `qw` and `qh` use 256 that means that the DB simplifies the geometries to be rendered in a 256*256 tile (typical raster scenario), so even though the final extent is 4096 overzooming is already broken.

**Comment by flippmoke** [comment]
Sorry, I missed the postgis plugin use -- I only saw the pgraster and other raster use. 

Do we actually want any simplification from postgis plugin here as MVT does its own simplification? I understand why this is useful for the mapnik renderer but the MVT renderer might not make sense here.

I am now not at all shocked to see any lacking differences in any of our tests as we do not do heavy testing of the postgis mapnik plugin through out our stack. This historically has been because it was harder to test and it is not heavily used at Mapbox. I know that a number of organizations are using this plugin outside Mapbox however and its really hard for me to judge how this will change results.

**Comment by Algunenano** [comment]
> Do we actually want any simplification from postgis plugin here as MVT does its own simplification? I understand why this is useful for the mapnik renderer but the MVT renderer might not make sense here.

We chose to disable the MVT simplification and use Postgis' because it saves up quite a bit of bandwidth between the DB server and the tiler producing the MVT.
Both simplification processes can be disabled:
- For `mapnik-vector-tile` by passing `simplify_distance : false` in the options to `map.render`.
- For the Mapnik's Postgis plugin by not using TWKB (`"twkb_encoding": false`) and nor both simplification, clipping or snapping (`"simplify_geometries": false, "simplify_clip_resolution": 0.0`). All this options are the default, so they are only active if demanded by the user.

Based on this, users with the default options won't be affected by this issue. The only 2 ways I see that you could be affected are:
- If like us, you have Postgis simplification enabled: You get oversimplified geometries.
- If you use the `pixel_height` or `pixel_width` tokens in your SQL query: In this case you'd get a pixel_width of `query_width / 256` instead of `query_width / mvt_extent`. Nevertheless I doubt anyone is using these tokens in their MVT queries since it doesn't really make sense to talk about pixels as there isn't any rendering going on.

**Comment by flippmoke** [comment]
@Algunenano :+1:

I am fine with merging this PR in now, I think the only debate is how we version this in node-mapnik and mapnik-vector-tile etc.

**Comment by Algunenano** [comment]
> I am fine with merging this PR in now, I think the only debate is how we version this in node-mapnik and mapnik-vector-tile etc.

I think there shouldn't be any issue in placing it with the rest of Mapnik 4 changes. Since Mapnik 4 isn't released yet, node-mapnik 4 should be considered a a pre-release too, so the changes could go into node-mapnik 4.0.2. In the same way, as `mapnik-vector-tile` 2.x is only compatible with Mapnik 4, it could be added as `2.3.0`.

Also, unless I'm mistaken, the idea of using an extend of 4096 by default was to enable overzooming which requires the geometries to be less simplified than for raster tiles. Having the geometries simplified for a 256x256 tile when using the Postgis plugin simplification is a bug, so this should be considered a bugfix which only requires a patch release.

Not that I mind it too much since we are still using Mapnik 3.0.x which means keeping forks until we can migrate to Mapnik 4 and, when we do, we won't mind if that means using node-mapnik 4.1 or 5.0. So, in short, I'm fine with whatever works with you.

**Comment by pnorman** [comment]
> node-mapnik 4 should be considered a a pre-release too

No, node-mapnik v4.0.0 is released, which is not a prerelease according to semver.
