### ISSUE TITLE
Strange Build Failure Building on Fedora 30 Docker Container Against Installed Mapnik HEAD

### ISSUE THREAD

**Issue by basking2** [mapbox/mapnik-vector-tile#294]
The attached [Dockerfile.txt](https://github.com/mapbox/mapnik-vector-tile/files/3210139/Dockerfile.txt) installs mapnik but fails to build mapnik-vector-tile against the installed library. The failure appears to be linking protobuf-light libraries. This error is observed in other issue reports (#187 ) in this project.

What is strange, and why I open a new ticket, is that if I append `2>1 | tee make.log` to the build command, the build completes successfully. 

Specifically, if you change line 21 of the attached file to `make release_base V=1 2>1 | tee make.log && \` then the build works.

To reproduce...

1.  Download the attached `Dockerfile.txt` and rename it to `Dockerfile`.
2. Run `docker build -t mybuild .` in the directory with the `Dockerfile` in it.

You should observe link errors similar to

```
/usr/bin/ld: ./Release/obj.target/tests/test/unit/processor/reprojection_error.o: in function `____C_A_T_C_H____T_E_S_T____17()':
reprojection_error.cpp:(.text+0x841): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: reprojection_error.cpp:(.text+0x13b2): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: reprojection_error.cpp:(.text+0x2192): undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
...
```

**Comment by pnorman** [comment]
> What is strange, and why I open a new ticket, is that if I append `2>1 > | tee make.log` to the build command, the build completes successfully.

That is bizarre. You have an extra `>` in that line - is that in error?

If you just append `2>1`, does it work?

**Comment by basking2** [comment]
Good call. The `| tee...` is masking the exit code and I think my STDERR redirect is wrong, and just putting errors into a file named "1".

I'm a bit confused why this link error would happen at all. Should I make a separate issue for that or should we keep this one open?

**Comment by basking2** [comment]
In Fedora 36 I observe that there is no longer a `boost-python2` library. As such, this issue seems to have aged.

Closing as Fedora 30 is well EOL.
