### ISSUE TITLE
dropping coincident points across features

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#3]
Currently we support dropping coincident vertices within a geometry, but not across features. In the case of many dense point features we could provide a mechanism to drop entire features whose point geometry are fully coincident with previously rendered points. This would not be ideal for cases where a client might want to keep all features interactive/clickable, but for all other cases this would drastically reduce the payload of the tiles.

Open issues if implemented:

 - Which points should "win": the first rendered or the last?
 - Optimized methods for checking for duplication in pixel space across features - quadtree/kdtree/rtree?

**Comment by flippmoke** [comment]
Closing this ticket for a couple reasons:

- Some of this deals with the vector tile specification directly
- There has been a lot of effort in mapnik-vector-tile since this was created
- Removal of duplicate or unioning of geometry objects within a feature already does exist
