### ISSUE TITLE
Consider storing more layer properties

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#34]
Currently, as encoded, layers are pretty simple and dumb. This was an intentional design but has limitations. It makes it hard to know critical details about them without fully decoding them or without having metadata from elsewhere.

For example:

 - Tiles with differing z,x,y should be able to be concatenated. If we encoded z,x,y inside the layer then decoding could be easily sensitive to the individual layer's tile extents.
 - If we encoded the buffer-size used to originally clip vtile geometries then we could easily know this extent upon decoding without decoding and introspecting each geometry.

**Comment by flippmoke** [comment]
I am closing this as some of this deals directly with the vector-tile-specification rather then with mapnik-vector-tile specifically. https://github.com/mapbox/vector-tile-spec/
