### ISSUE TITLE
Saving more bytes

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#4]
Running list of ideas for more space optimizations:

 - [ ] - Make the first moveto command implicit (i.e. 1 moveto command comes at the beginning of every geometry). In the case of points, we'd just encode the two points.
 - [ ] - Avoid explicitly storing the geometry type, instead detect points (2 commands) vs lines (>= 2 commands, not closed)  vs polygons (>= 3 commands, closed).
 - [ ] - Sort key/value dictionary by frequency
 - [ ] - Eliminate repeated `close path` commands in the case of geometry transformations leaving them behind
 - [ ] - Use shortest encoding for integers (negative/unsigned ints)
 - [ ] - Enable way to use float encoding, rather than double
 - [ ] - Expose option to drop encoding feature id's if not needed/meaningful

**Comment by flippmoke** [comment]
Many of these have been done as part of the mapnik vector tile work for the v2 specification, others deal with the specification itself. Closing this issue.
