### ISSUE TITLE
Purpose of sharp_turn_ahead and tolerance?

### ISSUE THREAD

**Issue by hallahan** [mapbox/mapnik-vector-tile#46]
`tolerance` seems to usually be set to 32, and I somewhat understand this to make sense in that we want to ignore drawing a stroke twice on something that is within the same pixel. 32 makes sense to me, because that would be what you need to get a valid pixel that is hypoteneuse from a given pixel. Then, to do stroke for adjacent pixels, `sharp_turn_ahead` would flag as true and the stroke would be made as an override.

In particular, I'm looking at:
https://github.com/mapbox/mapnik-vector-tile/blob/aeced9e341e96857211771995de99f5d9e3e84c0/src/vector_tile_geometry_encoder.hpp#L128

This means that tolerance is only effective for obtuse angles, and acute / 90deg angles would continue to be super sampled x 16. Why do we want to do this at all? My guess is that when mapnik renders the pbf to png, it will anti-alias sharp turns and points that exist within the previous pixel. Is this why?

I do see that turning off tolerance altogether for the most precise pbf zoom level makes sense, because we want non-simplified geometry for all subsequent rendered tiles. I suppose not using a `path_multiplier` would take away this benefit, Still, we could potentially just use the path_multiplier of 16 for the closest zoom level and not use it for others.

**Comment by springmeyer** [comment]
sharp_turn_ahead and tolerance are now gone from the library, closing.
