### ISSUE TITLE
Working with terrain data in vector tiles

### ISSUE THREAD

**Issue by joedoe101** [mapbox/mapnik-vector-tile#47]
I'm trying to find more information on how to work with terrain data in vector tile format. There is [Working with terrain data](https://www.mapbox.com/tilemill/docs/guides/terrain-data/) at mapbox.com which details how to render maps in TileMill, but it uses SRTM data converted to raster data (GeoTiff).

Recently [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) was released which uses terrain data in vector tiles.

I'd like some guidance on how to add terrain data, probably from [CGIAR](http://srtm.csi.cgiar.org/) or another source, into postgis and later generate and style vector tiles in mapnik.
I'm particularly interested in hillshades and slopes, since contours can be imported with gdal_contour.

Any information would be appreciated.

**Comment by springmeyer** [comment]
I recommend using a tool like gdal_polygonize to turn your raster data into vectors and then load into https://github.com/mapbox/mapbox-studio to render vector tiles. This is basically how the terrain data (contours) is produced that is available in the mapbox-gl-native default styles. Continuous raster support is not going to be as fast or flexible as true vectors. But descrete rasters may work in vtiles and keep an eye on #73 for experimentations around that.
