### ISSUE TITLE
Polygon winding order & holes vs outer rings

### ISSUE THREAD

**Issue by mourner** [mapbox/mapnik-vector-tile#59]
Do geometry rings have a defined winding order in vector tiles? E.g. counter-clockwise for outer rings and clockwise for rings? Or should I expect any order of any particular ring? 

Winding order isn't mentioned anywhere in spec, but some polygon algorithms depend on a certain winding order. Also, some algorithms (especially triangulation) need to know if a polygon ring is a hole or an outer ring, which could also be derived from winding order if geometry is flattened.

**Comment by mourner** [comment]
Another thing to note is that Mapnik VT output doesn't have `outer1, inner1, inner1, ..., outer2, inner2, ...` order — it can have outer rings and holes mixed up in random order, which is a problem when you're [trying to figure out which is which](https://github.com/mapbox/mapbox-gl-js/issues/682#issuecomment-70696189).

**Comment by mourner** [comment]
Another approach is to just split MultiPolygons into several Polygon features. This is how Mapzen solved the issue: https://github.com/mapzen/mapbox-vector-tile/issues/4

**Comment by bcamper** [comment]
@mourner yep, not an ideal solution, it would be nice to have multi-geometries directly supported in the spec.

**Comment by springmeyer** [comment]
Update here: my plan is to have mapnik-vector-tile ensure:

  - 1) exterior rings are encoded as CCW
  - 2) interior rings are encoded as CW
  - 3) interior rings always follow exterior rings

So, here are some examples then of how you would decode:

- `CCW` -> single polygon, no interior rings
- `CCW,CW,CW` -> single polygon, two interior rings
- `CCW,CCW,CCW` - > Multipolygon with 3 polygons, each with only an exterior ring
- `CCW,CCW,CCW,CW` - > Multipolygon with 3 polygons, each with one exterior ring, and the final one with one exterior ring and one interior ring
- `CW` -> single interior ring: degenerate, throw it out

As part of this push we need to ensure these winding order expectations are consistently maintained at a variety of steps. To that end I'll update the below set of check boxes as things progress:

 - [ ] Respect and/or correct winding order when decoding geometries from postgis, shapefiles, geojson, etc into internal structure. Shapefile window order already matches or expectation so we should not need to do anything. PostGIS and Geosjon make no promises so we'll correct on the fly.
 - [ ] When transforming, reprojecting
 - [ ] When simplifying
 - [ ] When clipping
 - [ ] When encoding polygon rings into protobuf geometries
 - [ ] When decoding back into internal structure
 - [ ] Test coverage to explore when/to what extent self-intersections will break the ability to detect winding order
 - [ ] Test coverage to explore when/to what extent degenerate exterior rings might break assumptions of ring order and how geometry culling will need to play this smart: #99

 - Work is happening at #94
 - Depends on https://github.com/mapnik/mapnik/labels/mapnik-geometry

**Comment by springmeyer** [comment]
This ticket is now resolved thanks to the work of many. Going to close with a short recap:

  - The Mapbox Vector Tile Specification version 2 clarified how winding order and ring order should be: https://www.mapbox.com/vector-tiles/specification/. The winding order must be CW for exterior rings when viewed in screen coordinates (it will be the reverse, CCW in geographical coordinates)
  - The spec text is at https://github.com/mapbox/vector-tile-spec/tree/master/2.1
  - The mapnik-vector-tile encoder now adheres to the v2 spec as of >= v1.0.1 (https://github.com/mapbox/mapnik-vector-tile/blob/master/CHANGELOG.md#100)

https://www.mapbox.com/blog/vector-tile-spec-changes/ is a good resource to learn more about what changed.
