### ISSUE TITLE
Vector tiles renderer ignores zoom level

### ISSUE THREAD

**Issue by plashchynski** [mapbox/mapnik-vector-tile#60]
Hello,

I'm trying to render vector tiles using node-mapnik mapnik.VectorTile feature:
```
var map = new mapnik.Map(256, 256);
var mercator = new sphericalmercator({size: 256});
map.loadSync("../openstreetmap-carto/openstreetmap-carto.xml");
var bbox = mercator.bbox(0,0,0, false, "900913");
map.zoomToBox(bbox);
var vtile = new mapnik.VectorTile(0, 0, 0);
map.render(vtile,{},function(err,vtile) {fs.writeFileSync('0.vector.pbf', vtile.getData());});
```

I use the standard openstreetmap-carto stylesheets. When I render it to png tiles, the 0-level zoom tile is a few kilobyte file that contains a simple image of the earth. When I render it to 0-level zoom vector.pbf using the code, the result .pbf file is a large file that seems to have all the map features on the 0-level zoom. How can we use the same zoon-related rules to keep 0-level zoom as simple as it rendered on png? Thank you.

**Comment by springmeyer** [comment]
Not sure why I re-opened this. Will close now with the parting note that I think openstreetmap-carto now has min/max zoom at the layer level now thanks to @pnorman.

**Comment by pnorman** [comment]
Yes, OpenStreetMap Carto now can be used to create vector tiles. There's still a bunch of big issues like returning areas instead of points for labeling, but nothing blows up.

**Comment by am2222** [comment]
@springmeyer  Hi,
I noticed about this issue, I was wondering if styles's based on feature attributes suffer from this issue? For example I have an style such as
```
<Style name="amenity_z13" filter-mode="first">
  <Rule>
    <MaxScaleDenominator>12500</MaxScaleDenominator>
    <Filter>([color] = 4)</Filter>
    <MarkersSymbolizer fill="#ac39ac" file="icons/[icon]-15.svg" placement="interior" clip="false" />
  </Rule>
</style>
```

When I try to render it from vector tile I face this error

`Mapnik LOG> 2018-03-15 07:51:19: Marker does not exist: /home/m/3.0.16/demo/c++/icons/-11.svg
`

which indicates that the `field` of  `[icon]` does not exist in feature which is retried from vector tile, but I can easily render map using this style with normal xml file
