### ISSUE TITLE
raster allocation optimizations

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#61]
https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_processor.hpp needs the same treatment as mapnik saw in https://github.com/mapnik/mapnik/commit/aaae8b1cbae9fab7903a912e8f2a2d48fe957b84#diff-e6b967728b887a3988f89dd623d07554

**Comment by flippmoke** [comment]
I believe this is done, but if it is not is very outdated.
