### ISSUE TITLE
MultiPoint geometries only draw one point

### ISSUE THREAD

**Issue by e-n-f** [mapbox/mapnik-vector-tile#62]
@springmeyer, as we just discussed on chat, I have been trying to use multipoint geometries in Mapbox Studio.

As a test, I uploaded [this GeoJSON file](http://trafficways.org/multipoint/multipoint3.geojson) to mapbox.com as map ID enf.tqgmbo6r.

It looks like each MultiPoint draws as a single point at the centroid of the points within each feature within each tile rather than drawing all the points, regardless of how marker-multi-policy is set:

![screen shot 2014-10-01 at 5 32 01 pm](https://cloud.githubusercontent.com/assets/1951835/4485451/b8dc59e8-49cb-11e4-82ed-3cdb5f4a6e99.png)

As individual points (enf.6vjqncdi) it looks like this:

![screen shot 2014-10-01 at 5 35 03 pm](https://cloud.githubusercontent.com/assets/1951835/4485466/0bb84db6-49cc-11e4-8758-756e735e9829.png)

but the file is twice as large with each point in its own feature.

**Comment by pnorman** [comment]
Does #98 and multipoints not existing in the spec change this?

**Comment by springmeyer** [comment]
@pnorman multipoints are supported in the spec and always have been: they are `type` `POINT` and encoded as multiple `move_to` commands rather than just one (for a single point).
