### ISSUE TITLE
Supporting single/multiband data rasters

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#73]
TODO:

  - [x] support encoding all pixel types in protobuf bytearray
  - [ ] ensure roundtripping of pixels after decoding

**Comment by flippmoke** [comment]
@springmeyer @artemp Added support grayscale images, just needs some new unit tests for round trip.

**Comment by springmeyer** [comment]
> where's the spec for what needs supporting?

@pnorman - no spec yet, we're still experimenting before forming up a concrete plan for the spec.

**Comment by flippmoke** [comment]
While we do not support multiband rasters and have no plan to currently, we have implemented a basic set of features for rasters in mapnik-vector-tile. A full fledged update to the specification should follow if it is decided that vector tiles SHOULD be able to contain raster images.
