### ISSUE TITLE
Make Issues on Master

### ISSUE THREAD

**Issue by ShibaBandit** [mapbox/mapnik-vector-tile#87]
Encountered make issue with master branch of vector tiles. Compiling with this setup used to work. I'm on ubuntu 14.04. Using '"libprotobuf8", "libprotobuf-dev", "protobuf-compiler"' packages. Using master branch of mapnik and vector tiles.  Any help is appreciated. I noticed there were some changes to dependencies on recent commits, do I need to update?

```
       ---- Begin output of make ----
       STDOUT: make[1]: Entering directory `/tmp/kitchen/cache/mapnik-vector-tile/build'
         LINK(target) Release/tests
       make[1]: Leaving directory `/tmp/kitchen/cache/mapnik-vector-tile/build'
       STDERR: /usr/bin/ld: ./Release/obj.target/tests/test/test_utils.o: undefined reference to symbol '_ZN6icu_5213UnicodeStringD1Ev'
       //usr/lib/x86_64-linux-gnu/libicuuc.so.52: error adding symbols: DSO missing from command line
       collect2: error: ld returned 1 exit status
       make[1]: *** [Release/tests] Error 1
       make: *** [libvtile] Error 2
       ---- End output of make ----
       exited unsuccessfully (exit code 1)
```

**Comment by flippmoke** [comment]
Is `icu` installed?

`sudo apt-get install icu`

**Comment by ShibaBandit** [comment]
I have icu-devtools, no icu package in my current repos. icu-config --version = 52.1

**Comment by ShibaBandit** [comment]
Tried your icu_linking build along with using the bootstrap.sh, fixed icu dependency but then got make errors:

```
./Release/obj.target/gyp/../mapnik_vector_tile_impl/src/vector_tile_backend_pbf.o: In function `mapnik::vector_tile_impl::backend_pbf::start_tile_feature(mapnik::feature_impl const&)':
vector_tile_backend_pbf.cpp:(.text+0x772): undefined reference to `u_strToUTF8_54'
vector_tile_backend_pbf.cpp:(.text+0x7d4): undefined reference to `u_strToUTF8_54'
vector_tile_backend_pbf.cpp:(.text+0xa07): undefined reference to `icu_54::UnicodeString::UnicodeString(icu_54::UnicodeString const&)'
vector_tile_backend_pbf.cpp:(.text+0xb82): undefined reference to `icu_54::UnicodeString::UnicodeString(icu_54::UnicodeString const&)'
vector_tile_backend_pbf.cpp:(.text+0xbc4): undefined reference to `icu_54::UnicodeString::UnicodeString(icu_54::UnicodeString const&)'
./Release/obj.target/gyp/../mapnik_vector_tile_impl/src/vector_tile_backend_pbf.o: In function `mapnik::value_adl_barrier::value::operator==(mapnik::value_adl_barrier::value const&) const':
vector_tile_backend_pbf.cpp:(.text._ZNK6mapnik17value_adl_barrier5valueeqERKS1_[_ZNK6mapnik17value_adl_barrier5valueeqERKS1_]+0xa9): undefined reference to `icu_54::UnicodeString::doEquals(icu_54::UnicodeString const&, int) const'
./Release/obj.target/gyp/../mapnik_vector_tile_impl/src/vector_tile_backend_pbf.o: In function `unsigned long mapnik::mapnik_hash_value<mapnik::value_adl_barrier::value>(mapnik::value_adl_barrier::value const&)':
vector_tile_backend_pbf.cpp:(.text._ZN6mapnik17mapnik_hash_valueINS_17value_adl_barrier5valueEEEmRKT_[_ZN6mapnik17mapnik_hash_valueINS_17value_adl_barrier5valueEEEmRKT_]+0x36): undefined reference to `icu_54::UnicodeString::doHashCode() const'
collect2: error: ld returned 1 exit status

```

**Comment by springmeyer** [comment]
@ShibaBandit - thanks for reporting. Can you share (the first time you hit the error) how you built mapnik ?

Also can you try this patch:

```diff
diff --git a/gyp/build.gyp b/gyp/build.gyp
index feb1532..8f031a2 100644
--- a/gyp/build.gyp
+++ b/gyp/build.gyp
@@ -106,6 +106,7 @@
         'libraries':[
           '<!@(mapnik-config --libs)',
           '<!@(mapnik-config --ldflags)',
+          '<!@(mapnik-config --dep-libs)',
           '-lprotobuf-lite',
           '-lz'
         ],
```

**Comment by ShibaBandit** [comment]
Has the preferred build from source method changed to use the bootstrap.sh? Should we be using that primarily? 

I think the install involves roughly most of the internet, we do:

Update-get update
Python
ubuntu-toolchain-r http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu

---------GDAL--------
Packages:
"cmake", "swig", "libhdf5-dev", "libnetcdf-dev", "netcdf-bin",
"libjbig-dev", "libpng-dev"

gdal-1.11.0 from source
geos-3.4.2 from source
tiff-4.0.3 from source
openjpeg-2.0.0 from source

---------Mapnik--------
Packages:
"gcc-4.9", "g++-4.9",
"libboost1.55-all-dev", "libcairo-dev", "libproj-dev", "libxml2-dev",
"libicu-dev", "libfreetype6-dev"

harfbuzz-0.9.37 from source

Mapnik from master mapnik/mapnik master branch. g++-4.9, gcc-4.9.

---------Mapnik Vector Tiles--------
Packages:
"libprotobuf8", "libprotobuf-dev", "protobuf-compiler"

Mapnik vector tiles from master.

**Comment by ShibaBandit** [comment]
Got a './build/Release/obj/gen/vector_tile.pb.cc' with the patch listed above.

**Comment by springmeyer** [comment]
@ShibaBandit not following what you mean by the above comment? Do you mean you hit an error?

**Comment by springmeyer** [comment]
> Has the preferred build from source method changed to use the bootstrap.sh? Should we be using that primarily?

@ShibaBandit - bootstrap.sh is primarily designed for travis so that we can run tests without using `sudo` and leverage http://docs.travis-ci.com/user/workers/container-based-infrastructure/. So, what you are trying to do should work still (build against external mapnik) as long as you are running the latest Mapnik 3.x from master github.

**Comment by ShibaBandit** [comment]
@springmeyer Sorry, I mean to say it builds with your patch. Make completes.

**Comment by springmeyer** [comment]
@ShibaBandit ah, fantastic, I'll push that fix then, thanks.
