### ISSUE TITLE
Update Ubuntu Instructions in README

### ISSUE THREAD

**Issue by flippmoke** [mapbox/mapnik-vector-tile#88]
The appear out of date as new MVT versions no longer support mapnik 2.x

**Comment by springmeyer** [comment]
I intended to address this in https://github.com/mapbox/mapnik-vector-tile/commit/fef084c2b3d4966b817174ea8338c933db9c056f#diff-04c6e90faac2675aa89e2176d2eec7d8. Please push further fixes if you see ways to improve / make the 2.x support issue more obvious.
