### ISSUE TITLE
python bindings

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#9]
Currently as far as bindings, we have fully fledged [node.js bindings](https://github.com/mapnik/node-mapnik/compare/master...vector-tile), but for python currently only a set of examples for usage exists at https://github.com/mapbox/mapnik-vector-tile/tree/master/python which do not actually use mapnik.

Task here is to write python bindings against mapnik to enable things like a custom provider in TileStache.

**Comment by springmeyer** [comment]
Not planning on python bindings to this module. If anyone is interested in Vector Tiles from python checkout https://github.com/mapzen/mapbox-vector-tile

**Comment by am2222** [comment]
So there is not any method to render vector tiles using mapnik, is it?

**Comment by flippmoke** [comment]
Not currently, there are various sets of pure python ways to do it currently.

**Comment by palmerj** [comment]
What about the ability to render raster tiles from vector tile source? https://github.com/mapbox/tilelive-vector. https://github.com/mapzen/mapbox-vector-tile doesn't help with that.
