### ISSUE TITLE
optimized vector_tile_datasource that works directly on protobuf buffer

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#92]
Currently `vector_tile_datasource` and `vector_tile_featureset` expect to work on the google protobuf created `vector_tile::Tile_Layer`. This `vector_tile::Tile_Layer` structure is convenient but heavy. The intermediate objects are fast to access but require significant memory to allocate (and significant time to deallocate). A potentially much lower memory approach and faster approach would be:

 - when we know we are in read-only mode...
 - use [pbf.hpp](https://github.com/mapbox/pbf.hpp) to lazily parse protobuf messages
 - slices sections of a protobuf representing each layer
 - pass those slices of data into `vector_tile_datasource`
 - re-write the internals of `vector_tile_datasource` to parse out features and geometries with pbf.hpp

The obvious drawback of this approach is that `pbf.hpp` is very low level. Because it does not allocate anything (which is good!) using it requires a lot of while loops to grab the right data at the right time. This makes it easy to write bugs that access invalid memory. But, I think the performance benefit is worth - especially when compositing vector tiles when overzooming is involved. In this latter case I've seen large stacks of heavy vector tiles (like the one that back https://www.mapbox.com/blog/twitter-map-every-tweet/) using > 7 GB of memory to composite and 70% of that is in the wasteful allocations inside libprotobuf.

TODO:

  - [x] pull in @artemp's fixes to pbf.hpp from https://github.com/mapnik/mapnik/blob/geobuf/plugins/input/geobuf/pbf.hpp - DONE thanks to @joto in https://github.com/mapbox/pbf.hpp/issues/5
  - [x] better test coverage of pbf.hpp before starting this - done thanks to @joto at https://github.com/mapbox/pbf.hpp/blob/master/test/README.md
  - [x] ~~port read-only uses of protobuf objects from libprotobuf to pbf.hpp in mapnik-vector-tile~~ - now have both implementations in parallel
  - [ ] re-write node-mapnik's internals to serialize vector tile objects to a protobuf string everytime a write is made to the vector tile: This would allow all read methods in node-mapnik to use pbf.hpp rather than ever needing to keep around the `vector_tile::Tile` object that gets created when writing to a vector tile.

**Comment by danpat** [comment]
I'm workin' on this one.

**Comment by flippmoke** [comment]
@danpat Please coordinate with me on this some, I have some design ideas that I want to talk out with you.

**Comment by danpat** [comment]
As a start on this, I've got a roughly working read-only `vector_tile_datasource` that passes some basic test cases.  It's sitting in `master` in a fork at [danpat/mapnik-vector-tile](https://github.com/danpat/mapnik-vector-tile).  @flippmoke - Are there any big vector tiles lying around to do a memory/speed performance comparison with?

**Comment by flippmoke** [comment]
@ajashton know of any really large OSM tiles?

**Comment by pnorman** [comment]
How big do you want?

**Comment by danpat** [comment]
Big enough to make it easy to see affects on memory usage.  How big do they get?  @flippmoke mentioned that 10MB v_tiles consumed 100MB+ memory when read.  That kind of size would work for the tests I have in mind.

**Comment by pnorman** [comment]
http://www.paulnorman.ca/files/5_16_11.pbf 50MB
http://www.paulnorman.ca/files/6_20_20.pbf 10MB

Both uncompressed sizes, both generated from OpenStreetMap Carto as described in [a blog post of mine](http://www.paulnorman.ca/blog/2015/05/avecado-and-a-stylesheet/).

This means they are 8x8 metatiles for 8/128/88 and 9/160/160.

They cover 
![image](https://cloud.githubusercontent.com/assets/1190866/7870317/5882e25a-053d-11e5-840e-65ee6e88cfa4.png)
![image](https://cloud.githubusercontent.com/assets/1190866/7870321/6235ee96-053d-11e5-9286-4c7a8e9681e1.png)

They are not optimized for vector tile rendering.

**Comment by danpat** [comment]
@pnorman - thanks.

I wrote two test cases, one that loads the big PBF using the Google protobuf generated API, the other uses the new `pbf.hpp` datasource implementation.  Then, using a minimal (single rule) stylesheet, a single 512x512 tile is generated using the AGG renderer.  The generated tile is blank.

Assuming I got it right, peak memory usage is down by ~65%, tile parsing time down by ~80%.

    $ /usr/bin/time -l build/Release/tests "basic pbf rendering using Google Protobuf"
    1 test case - passed (no assertions)  ✓
            2.23 real         1.87 user         0.31 sys
    491,753,472  maximum resident set size

    $ /usr/bin/time -l build/Release/tests "basic pbf rendering using pbf.hpp"
    1 test case - passed (no assertions) ✓
            0.46 real         0.36 user         0.10 sys
    158,457,856  maximum resident set size

I suspect for big tiles that parsing time will be dwarfed by other factors (actually rendering), but the reduction in peak memory usage is pretty big.  The code is not really any more complex, although we do lose compile-time type checking on the vector tile protobuf API.

@flippmoke - I think I will need a bit more guidance to take this too much further.  I can see the various pieces where vector_tile::Tile needs to be pulled out, and I have a very rough understanding of what you were describing the other day, but there's a whole lot more complexity on the compositing side that I have very little insight to at this stage.

There might be another quick win to create a clone of `vector_tile_backend_pbf.hpp` that operates on a `pbf.hpp::pbf_writer`, but it's not clear to me whether that interface would need to change to support more efficient compositing.

**Comment by springmeyer** [comment]
capturing chat: @danpat and I have been chatting about this today. The summary and next actions are:

  - we'll keep both datasource implementations around for now, and therefore will test both
  - read-only is all that is needed as this point
  - @danpat is working next on tests to ensure that invalid (like truncated tiles) don't crash but rather produce expected exceptions.

**Comment by springmeyer** [comment]
Awesome work on #114 @danpat - it is now merged. Will tag `v0.8.1` shortly with this inside.

As per [overall tasks](https://github.com/mapbox/mapnik-vector-tile/issues/92#issue-62610372) next step is:

> re-write node-mapnik's internals to serialize vector tile objects to a protobuf string everytime a write is made to the vector tile: This would allow all read methods in node-mapnik to use pbf.hpp rather than ever needing to keep around the vector_tile::Tile object that gets created when writing to a vector tile.

This will be tricky and we'll likely learn some gochas along the way. But I think the mapnik-vt work is enough for now to push on the node-mapnik side. So, closing this and will start pushing on https://github.com/mapnik/node-mapnik/issues/419.
