### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapnik-vector-tile#95]
Code coverage I think is going to be poor for this repo, so will be great to see. The changes coming up in #93 are large so coverage I think would make sense to start on after we merge #93 (or in the https://github.com/mapbox/mapnik-vector-tile/tree/mapnik-geometry branch).

A big reason why coverage is crap is the lack of a good harness in C++ for writing visual tests and/or tests that use external fixtures (like directory of expected geojson fixtures). So I think we should start on that. I still like the idea of this existing outside of mapnik.

Resources:

 - @talaj mentioned he's got a c++ runner going for visual tests in mapnik core: https://github.com/mapnik/mapnik/issues/2744#issuecomment-86835227 as part of https://github.com/mapnik/mapnik/issues/2575
 - code from https://github.com/mapnik/mapnik/blob/master/benchmark/bench_framework.hpp and https://github.com/mapnik/mapnik/blob/master/benchmark/compare_images.hpp could be stolen too
 - The JSON input and output grammars in the mapnik-geometry branch are way nicer now (since they work on `mapnik::geometry` objects rather than vertex_converters (aka paths) so using them to read and serialize fixtures would be great.

**Comment by pnorman** [comment]
@zerebubuth, @kevinkreiser and myself have written tests for Avecado which implicitly test m-v-t. We did some tests verifying PBF outputs and examining the Mapnik layers that m-v-t created.

**Comment by springmeyer** [comment]
#93 is now merged. It's time to move on this.

**Comment by springmeyer** [comment]
done in https://github.com/mapbox/mapnik-vector-tile/pull/104
