### ISSUE TITLE
Better simplification

### ISSUE THREAD

**Issue by mourner** [mapbox/mapnik-vector-tile#96]
In my gl-js tests, running simplify-js with tolerance=5 on all VT geometry pretty much doesn't affect visual appearance while reducing the total number of points in a dense DC view by a **whopping 54%**. It's smaller for lower zoom tiles but still significant — 21% on a z9 view with lots of water.

That's a HUGE low-hanging fruit for making our tiles smaller and tile processing/rendering performance better.

@springmeyer if we ditch the current simplification code and implement proper simplification like Douglas-Peucker, how much of an overhead would that be in context of the full VT pipeline?

**Comment by mourner** [comment]
Also, would it be possible to use @kkaefer's Visvalingam simplification in Mapnik (earlier in the pipeline) instead of doing that in mapnik-vector-tile? What would be the difference? cc @artemp

**Comment by artemp** [comment]
@mourner - what do you mean by "proper Douglas-Peucker" ? As oppose to "just skipping vertices" currently VT? I think we use DP in postgis queries - maybe we should to more aggressive simplification ( @aj?) Trying to understand here.

"Visvalingam simplification" is great when vertices weighted in advance and weight are stored. Then you just filter vertices using tolerance.

**Comment by mourner** [comment]
I didn't realize that we store the data in spherical mercator coords in the database. Then using the right values in PostGIS ST_Simplify should in theory give us the same result. We probably need to revisit tolerance values then.

**Comment by mourner** [comment]
Artem says we only need to apply point filtering in mapnik-vector-tile to remove dupes introduces by clipping. But we currently use [tolerance=8 for everything below max_zoom](https://github.com/mapbox/tilelive-bridge/blob/master/index.js#L160), which acts as a bad simplification (spoiling detailed geometry).

That means that if we do simplification in PostGIS just right (using perfect tolerance values), we can ditch the current routine and just dedupe exact coordinates. This way we'll have smaller tiles and better detailed geometries at the same time.

**Comment by mourner** [comment]
OK looking at https://github.com/mapbox/mapbox-streets-source.tm2source code that mentions st_simplify (e.g. [this code for roads](https://github.com/mapbox/mapbox-streets-source.tm2source/blob/v6/pgsql/carto_table_updates.sql#L537-L545)), it seems that we don't have proper per-zoom simplification at all. Which is very bad for GL. cc @ajashton

**Comment by flippmoke** [comment]
@mourner keep in mind that this is a double edge sword, too much simplification with out proper work can result in some ugly things that we don't want. 

Imagine a road like this:

![intersection](https://cloud.githubusercontent.com/assets/1794907/6897363/e188832e-d6b8-11e4-8e2d-0da2b7c6d3c4.png)

With out locking that point for an important intersection we might simplify it out entirely. This will make the map look strange. This might be something we have to process in mapnik internally, or an entire process  prior to handing to mapnik to make this all work out properly.

**Comment by springmeyer** [comment]
Simplification using DP algo in boost::geometry is working well in testing so far - this is a work in progress in https://github.com/mapbox/mapnik-vector-tile/pull/94. Out plan is to pause on pushing it until Mapnik upstream is ready which will happen when these tickets are closed: https://github.com/mapnik/mapnik/labels/mapnik-geometry

**Comment by flippmoke** [comment]
I think this ticket is closed?
